### ISSUE TITLE
Missing Prefab & script cannot be load problem

### ISSUE THREAD

**Issue by dhyLH** [sprphys/SprUnitySamples#1]
This is Ding 
I am using Unity 2017.3.1f1.
I cloned the SprUnitySamples and submodules.
When I open the project with Unity in the first time I update the project files for new Unity versions(mendatory).
Then  I open the scene such as RigidBody, start the simulation, no physical calculation is running
And I got This two
![sprerr3](https://user-images.githubusercontent.com/25602767/37138790-c3e13f7a-22ee-11e8-8a63-a7ed90990c16.PNG)
![sprerr1](https://user-images.githubusercontent.com/25602767/37138793-c5fee37a-22ee-11e8-918a-ed851f6c5e3f.PNG)
![sprerr2](https://user-images.githubusercontent.com/25602767/37138795-c87a9766-22ee-11e8-8be2-618c2b764dc7.PNG)

I already check the project files, all the scrips are cloned
![sprerr4](https://user-images.githubusercontent.com/25602767/37138962-705212a2-22ef-11e8-9365-228487d08fb8.PNG)

Maybe we have to use the same version of Unity?

Have you experince such problem?

**Comment by mitake-h** [comment]
It was because of I didn't commit *.meta files.

Now it is solved. Please clone the project again.
